version: 2

sphinx:
  configuration: astropixel/docs/source/conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.12"

python:
  version: 3.12
  install:
    - requirements: astropixel/docs/requirements.txt

