version: 2

sphinx:
  configuration: astropixel/docs/source/conf.py

python:
  version: 3.8
  install:
    - requirements: astropixel/docs/requirements.txt
  system_packages:
    - libatlas-base-dev
    - libopenblas-dev

formats: all
